/*
 * API for user admin panel
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: korotkov.ivan.s@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/iskorotkov/user-admin-panel-backend/api"
)

func main() {
	log.Printf("Server started")

	UsersApiService := api.NewUsersApiService()
	UsersApiController := api.NewUsersApiController(UsersApiService)

	router := api.NewRouter(UsersApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
