/*
 * API for user admin panel
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: korotkov.ivan.s@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// ImplResponse response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Headers map[string][]string
	Body interface{}
}
